export default {
    login: 'MJonny4',
    id: 92377687,
    node_id: 'U_kgDOBYGSVw',
    avatar_url: 'https://avatars.githubusercontent.com/u/92377687?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/MJonny4',
    html_url: 'https://github.com/MJonny4',
    followers_url: 'https://api.github.com/users/MJonny4/followers',
    following_url:
        'https://api.github.com/users/MJonny4/following{/other_user}',
    gists_url: 'https://api.github.com/users/MJonny4/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/MJonny4/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/MJonny4/subscriptions',
    organizations_url: 'https://api.github.com/users/MJonny4/orgs',
    repos_url: 'https://api.github.com/users/MJonny4/repos',
    events_url: 'https://api.github.com/users/MJonny4/events{/privacy}',
    received_events_url: 'https://api.github.com/users/MJonny4/received_events',
    type: 'User',
    site_admin: false,
    name: 'Ion',
    company: null,
    blog: 'https://www.ximuntion.dev/',
    location: 'Igualada',
    email: null,
    hireable: true,
    bio: 'Testing...',
    twitter_username: '_MJonny4',
    public_repos: 2,
    public_gists: 0,
    followers: 5,
    following: 5,
    created_at: '2021-10-12T12:54:56Z',
    updated_at: '2023-08-06T17:17:36Z',
};
